# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: mypool

steps:
- script: |
    .\myscript.sh 74.235.161.211:config_files src healthy:mycontainer && type script.log
  displayName: 'Run a multi-line script'
  
- script: |
    cd ..\..\ azcopy_windows_amd64_10.19.0\azcopy.exe copy 'configure_files/confiles-$name.tar.gz' 'https://$storage[0].blob.core.windows.net/$storage[1]/confiles-$name.tar.gz' >> script.log
  displayName: 'Run a one-line script'
