# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: mypool

steps:
- script: .\myscript.sh azureuser@74.235.161.211:config_files src healthy:mycontainer
  displayName: 'Run a multi-line script'

- script: type script.log
  displayName: 'Printing logs'
